name: imihirpaldhikar_portfolio
description: The Portfolio of iMihirPaldhikar
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  url_strategy: ^0.2.0
  universal_html: ^2.0.8
  font_awesome_flutter: ^9.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  responsive_builder: ^0.4.1
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets: 
   - assets/jpg/profile.jpg