name: imihirpaldhikar
description: The Portfolio of Mihir Paldhikar
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-10.0.dev <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  google_fonts: ^2.1.0
  url_strategy: ^0.2.0
  auto_size_text: ^3.0.0
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.15
  blobs: ^2.0.0
  flutter_markdown: ^0.6.8
  fl_chart: ^0.40.2
  flutter_native_splash: ^1.3.1
  universal_html: ^2.0.8
  responsive_builder: ^0.4.1
  http: ^0.13.4
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
flutter:
  uses-material-design: true
  assets:
   - assets/jpg/hero.png
   - assets/jpg/profile.jpg
   - website.config.env
